package models;
// Generated Jun 3, 2022 10:03:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private int id;
     private Marca marca;
     private String nume;
     private Set tiruris = new HashSet(0);

    public Model() {
    }

	
    public Model(Marca marca,String nume) {
        this.marca = marca;
        this.nume = nume;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public Set getTiruris() {
        return this.tiruris;
    }
    
    public void setTiruris(Set tiruris) {
        this.tiruris = tiruris;
    }

    @Override
    public String toString() {
        return "Modele{" + "id=" + id + ", marca=" + marca + ", nume=" + nume + '}';
    }
    
}


