package models;
// Generated May 12, 2022 5:57:09 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Tiruri generated by hbm2java
 */
public class Tir  implements java.io.Serializable {


     private int id;
     private Model model;
     private String nrInmatriculare;
     private Stare stare;
     private Set<SoferiTiruri> soferiTiruri = new HashSet<SoferiTiruri>(0);

    public Tir() {
    }

    public Tir(Model model, String nrInmatriculare, Stare stare) {
        this.model = model;
        this.nrInmatriculare = nrInmatriculare;
        this.stare = stare;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public String getNrInmatriculare() {
        return this.nrInmatriculare;
    }
    
    public void setNrInmatriculare(String nrInmatriculare) {
        this.nrInmatriculare = nrInmatriculare;
    }

    public Stare getStare() {
        return stare;
    }


    
    
    public void setStare(Stare stare) {
        this.stare = stare;
    }

    public Set<SoferiTiruri> getSoferiTiruri() {
        return soferiTiruri;
    }

    public void setSoferiTiruri(Set<SoferiTiruri> soferiTiruri) {
        this.soferiTiruri = soferiTiruri;
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    @Override
    public String toString() {
        return "Tir{" + "id=" + id + ", model=" + model + ", nrInmatriculare=" + nrInmatriculare + ", stare=" + stare + '}';
    }
}


