package models;
// Generated May 12, 2022 5:57:09 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Tiruri generated by hbm2java
 */
public class Tir  implements java.io.Serializable {


     private int id;
     private Model model;
    
     private String nrInmatriculare;
     private int idStare;
     private Stare stare;
     private Set<SoferiTiruri> soferiTiruri = new HashSet<SoferiTiruri>(0);

    public Tir() {
    }

    public Tir(int id, String model, String nrInmatriculare, int idStare) {
       this.id = id;
      
       this.nrInmatriculare = nrInmatriculare;
       this.idStare = idStare;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
 
    
    
    public String getNrInmatriculare() {
        return this.nrInmatriculare;
    }
    
    public void setNrInmatriculare(String nrInmatriculare) {
        this.nrInmatriculare = nrInmatriculare;
    }
    public int getIdStare() {
        return this.idStare;
    }
    
    public void setIdStare(int idStare) {
        this.idStare = idStare;
    }

   

    public Stare getStare() {
        return stare;
    }

    public void setStare(Stare stare) {
        this.stare = stare;
        if (stare!=null){
            this.idStare = stare.getId();
        }
    }

    public Set<SoferiTiruri> getSoferiTiruri() {
        return soferiTiruri;
    }

    public void setSoferiTiruri(Set<SoferiTiruri> soferiTiruri) {
        this.soferiTiruri = soferiTiruri;
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }




}


